name: Build and Deploy PreTeXt

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PreTeXt
        run: |
          pip install --upgrade pip
          pip install pretext

      - name: Build PreTeXt projects
        run: |
          mkdir -p public
          for course in Math1431 Math1432 Math2231 Math2232 Math2233; do
            if [ -d "$course" ]; then
              cd $course
              pretext build web
              cd ..
              mkdir -p public/$course
              cp -r $course/output/web/* public/$course/
            fi
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
